import axios from 'axios';
export const api=axios.create({baseURL:import.meta.env.VITE_API_BASE_URL||'https://api.paisakamao.com',withCredentials:true,headers:{'Content-Type':'application/json'}});
api.interceptors.request.use(c=>{const csrf=document.cookie.split('; ').find(v=>v.startsWith('csrfToken='))?.split('=')[1];if(c.method&&!['get','head','options'].includes(c.method.toLowerCase())&&csrf)c.headers['X-CSRF-Token']=csrf;return c;});
api.interceptors.response.use(r=>r,e=>{if(e.response?.status===401&&location.pathname!=='/login')location.assign('/login');return Promise.reject(e)});
const demo=import.meta.env.VITE_DEMO_MODE!=='false';
const users=[{id:101,name:'Aarav Sharma',mobile:'98•••••210',city:'Indore',balance:420,total_earned:1250,status:'active',kyc_status:'verified'},{id:102,name:'Priya Verma',mobile:'97•••••842',city:'Bhopal',balance:180,total_earned:680,status:'active',kyc_status:'pending'},{id:103,name:'Rohan Patel',mobile:'99•••••106',city:'Ujjain',balance:0,total_earned:240,status:'suspended',kyc_status:'pending'}];
const tasks=[{id:1,title_en:'Explore a finance offer',category:'finance',reward:25,cpa_payout:40,status:'active',completions:184},{id:2,title_en:'Compare insurance options',category:'insurance',reward:40,cpa_payout:70,status:'active',completions:96},{id:3,title_en:'Complete a wellness survey',category:'health',reward:15,cpa_payout:25,status:'paused',completions:241}];
const payouts=[{id:501,user:'Aarav Sharma',amount:350,upi_id:'aarav@upi',status:'pending',risk_score:12,requested_at:'2026-09-30 10:42'},{id:502,user:'Priya Verma',amount:500,upi_id:'priya@upi',status:'pending',risk_score:38,requested_at:'2026-09-30 11:16'}];
export async function request(path,options={}){if(!demo)return (await api.request({url:path,...options})).data;const method=(options.method||'GET').toUpperCase();if(path==='/api/admin/login'||path==='/api/admin/me')return {user:{name:'Demo Admin',email:'admin@example.com',role:'super_admin'}};if(path==='/api/admin/logout')return {};if(path==='/api/admin/stats')return {totalUsers:12840,activeUsers:4280,monthlyRevenue:824500,pendingPayouts:28450,userChange:12.4};if(path.startsWith('/api/admin/charts'))return {signups:[12,18,14,26,21,33,28,42,38,47,44,52].map((v,i)=>({day:i+1,value:v})),revenue:[{name:'Finance',value:42000},{name:'Insurance',value:31000},{name:'Health',value:18000}]};if(path==='/api/admin/users')return {items:users};if(path.startsWith('/api/admin/users/'))return users.find(u=>u.id===Number(path.split('/').pop()))||users[0];if(path==='/api/admin/tasks')return {items:tasks};if(path.startsWith('/api/admin/withdrawals'))return {items:payouts};if(path==='/api/admin/fraud/logs')return {items:[{id:1,user_id:103,type:'duplicate_device',severity:'high',created_at:'2026-09-30 09:20',action_taken:'under_review'}]};if(path==='/api/admin/settings')return {minWithdrawal:100,signupBonus:0,referralBonus:20,dailyTaskLimit:5,autoApproveThreshold:0};if(path==='/api/admin/admins')return {items:[{id:1,name:'Demo Admin',email:'admin@example.com',role:'super_admin',status:'active'}]};if(method!=='GET')return {ok:true};return {items:[]}}
